source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SuperTextView_Example', :exclusive => true do
  pod "SuperTextView", :path => "../"
end

target 'SuperTextView_Tests', :exclusive => true do
  pod "SuperTextView", :path => "../"

  
end
